WALL, PLAYER, PLAYER_ON_GOAL, BOX, BOX_ON_GOAL, GOAL, FLOOR = '#', '@', '+', '$', '*', '.', ' '

COMPONENTS = {WALL, PLAYER, PLAYER_ON_GOAL, BOX, BOX_ON_GOAL, GOAL, FLOOR}



UP, DOWN, LEFT, RIGHT = 'U', 'D', 'L', 'R'
ACTIONS = [UP, DOWN, LEFT, RIGHT]